// OpenNext's generated worker remains the request handler. This thin wrapper
// only adds the scheduled entrypoint needed by Cloudflare Cron Triggers.
// @ts-expect-error .open-next/worker.js is generated by build:worker.
import generatedWorker from "./.open-next/worker.js";

type WorkerEnv = {
  BILLING_CRON_SECRET?: string;
  WORKER_SELF_REFERENCE?: {
    fetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response>;
  };
};

const worker = generatedWorker as {
  fetch(request: Request, env: WorkerEnv, ctx: unknown): Response | Promise<Response>;
};

const customWorker = {
  fetch(request: Request, env: WorkerEnv, ctx: unknown) {
    return worker.fetch(request, env, ctx);
  },
  async scheduled(_controller: unknown, env: WorkerEnv, _ctx: unknown) {
    void _ctx;
    if (!env.WORKER_SELF_REFERENCE) throw new Error("WORKER_SELF_REFERENCE is not configured");
    const response = await env.WORKER_SELF_REFERENCE.fetch(
      new Request("https://progy-asistant/api/billing/run-cycle", {
        method: "POST",
        headers: { "x-billing-cron-secret": env.BILLING_CRON_SECRET || "" },
      }),
    );
    if (!response.ok) throw new Error(`Billing cycle failed with status ${response.status}`);
  },
};

export default customWorker;
