export const AUTH_EMAIL_MAX_LENGTH = 254;
export const AUTH_NAME_MAX_LENGTH = 120;
export const AUTH_PASSWORD_MIN_LENGTH = 8;
export const AUTH_PASSWORD_MAX_LENGTH = 128;
export const AUTH_REQUEST_MAX_BYTES = 16 * 1024;
export const AUTH_DEFAULT_EXPIRES_IN_SECONDS = 60 * 60;
export const AUTH_MAX_EXPIRES_IN_SECONDS = 24 * 60 * 60;
export const AUTH_REFRESH_COOKIE_MAX_AGE_SECONDS = 30 * 24 * 60 * 60;
